// <auto-generated />
using System;
using Controle_De_Estoque.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Controle_De_Estoque.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Controle_De_Estoque.Models.AttributeWoo", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("Productsid")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("options")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("variation")
                        .HasColumnType("bit");

                    b.HasKey("id");

                    b.HasIndex("Productsid");

                    b.ToTable("AttributeWoo");
                });

            modelBuilder.Entity("Controle_De_Estoque.Models.Attributes", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MercadoLivreid")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("value_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("value_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("MercadoLivreid");

                    b.ToTable("Attributes");
                });

            modelBuilder.Entity("Controle_De_Estoque.Models.EstoquePrincipal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Quantidade_Estoque")
                        .HasColumnType("int");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("produtos_MercadoLivreid")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("produtos_WooCommerceid")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("produtos_MercadoLivreid");

                    b.HasIndex("produtos_WooCommerceid");

                    b.ToTable("Estoque");
                });

            modelBuilder.Entity("Controle_De_Estoque.Models.Login.Login", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConfirmPassword")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.ToTable("Logins");
                });

            modelBuilder.Entity("Controle_De_Estoque.Models.Login.UserConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LoginId")
                        .HasColumnType("int");

                    b.Property<string>("MeliClientId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MeliClientSecret")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MeliRefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WooConsumerKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WooConsumerSecret")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WooUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("redirect_uri")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LoginId")
                        .IsUnique();

                    b.ToTable("UserConfig");
                });

            modelBuilder.Entity("Controle_De_Estoque.Models.Login.UserMeliToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Expire_in")
                        .HasColumnType("int");

                    b.Property<int>("LoginId")
                        .HasColumnType("int");

                    b.Property<string>("access_token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("datacriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("refreshtoken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("token")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LoginId")
                        .IsUnique();

                    b.ToTable("UserMeliToken");
                });

            modelBuilder.Entity("Controle_De_Estoque.Models.MercadoLivre", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("available_quantity")
                        .HasColumnType("int");

                    b.Property<string>("category_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("category_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("domain_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("domain_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("MercadoLivre");
                });

            modelBuilder.Entity("Controle_De_Estoque.Models.Products", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("Productsid")
                        .HasColumnType("int");

                    b.Property<DateTime>("date_created")
                        .HasColumnType("datetime2");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("permalink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sku")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("stock_quantity")
                        .HasColumnType("int");

                    b.Property<string>("variations")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("Productsid");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Controle_De_Estoque.Models.Variations", b =>
                {
                    b.Property<long>("variationsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("variationsId"));

                    b.Property<string>("MercadoLivreid")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("available_quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("seller_custom_field")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("variationsId");

                    b.HasIndex("MercadoLivreid");

                    b.ToTable("Variations");
                });

            modelBuilder.Entity("Controle_De_Estoque.Models.AttributeWoo", b =>
                {
                    b.HasOne("Controle_De_Estoque.Models.Products", null)
                        .WithMany("attributes")
                        .HasForeignKey("Productsid");
                });

            modelBuilder.Entity("Controle_De_Estoque.Models.Attributes", b =>
                {
                    b.HasOne("Controle_De_Estoque.Models.MercadoLivre", null)
                        .WithMany("attributes")
                        .HasForeignKey("MercadoLivreid");
                });

            modelBuilder.Entity("Controle_De_Estoque.Models.EstoquePrincipal", b =>
                {
                    b.HasOne("Controle_De_Estoque.Models.MercadoLivre", "produtos_MercadoLivre")
                        .WithMany()
                        .HasForeignKey("produtos_MercadoLivreid");

                    b.HasOne("Controle_De_Estoque.Models.Products", "produtos_WooCommerce")
                        .WithMany()
                        .HasForeignKey("produtos_WooCommerceid");

                    b.Navigation("produtos_MercadoLivre");

                    b.Navigation("produtos_WooCommerce");
                });

            modelBuilder.Entity("Controle_De_Estoque.Models.Login.UserConfig", b =>
                {
                    b.HasOne("Controle_De_Estoque.Models.Login.Login", "Login")
                        .WithOne("UserConfig")
                        .HasForeignKey("Controle_De_Estoque.Models.Login.UserConfig", "LoginId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Login");
                });

            modelBuilder.Entity("Controle_De_Estoque.Models.Login.UserMeliToken", b =>
                {
                    b.HasOne("Controle_De_Estoque.Models.Login.Login", "login")
                        .WithOne("UserMeliToken")
                        .HasForeignKey("Controle_De_Estoque.Models.Login.UserMeliToken", "LoginId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("login");
                });

            modelBuilder.Entity("Controle_De_Estoque.Models.Products", b =>
                {
                    b.HasOne("Controle_De_Estoque.Models.Products", null)
                        .WithMany("variationsProducts")
                        .HasForeignKey("Productsid");
                });

            modelBuilder.Entity("Controle_De_Estoque.Models.Variations", b =>
                {
                    b.HasOne("Controle_De_Estoque.Models.MercadoLivre", null)
                        .WithMany("variations")
                        .HasForeignKey("MercadoLivreid");
                });

            modelBuilder.Entity("Controle_De_Estoque.Models.Login.Login", b =>
                {
                    b.Navigation("UserConfig");

                    b.Navigation("UserMeliToken");
                });

            modelBuilder.Entity("Controle_De_Estoque.Models.MercadoLivre", b =>
                {
                    b.Navigation("attributes");

                    b.Navigation("variations");
                });

            modelBuilder.Entity("Controle_De_Estoque.Models.Products", b =>
                {
                    b.Navigation("attributes");

                    b.Navigation("variationsProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
